# Generated by Django 4.1 on 2022-09-03 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgePreds",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_time", models.DateTimeField()),
                ("image_input", models.TextField()),
                ("results_output", models.TextField()),
            ],
        ),
    ]
