# Generated by Django 4.1 on 2022-09-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aeapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="AgePreds", new_name="AgePrediction",),
    ]
